### ISSUE TITLE
Slight mistype in your README file

### ISSUE THREAD

**Issue by jcrooke** [chillerlan/php-cache#1]
Hi there,

Thanks for this cache library, I used it in a prototype testing various cache methods - worked a treat!

One thing that tripped me up however was the following README example;

```
// File
$cache = new FileCache(new CacheOptions(['filestorage' => __DIR__.'/../.cache']));
```

Should be;

```
// File
$cache = new FileCache(new CacheOptions(['cacheFilestorage' => __DIR__.'/../.cache']));
```

i.e. *filestorage* should be *cacheFilestorage*

Thanks!

**Comment by codemasher** [comment]
Thanks! (completely forgot about this one)
