### ISSUE TITLE
support new versions of PHP (8.1, 8.2 and 8.3)

### ISSUE THREAD

**Issue by khanzadimahdi** [chillerlan/php-cache#3]
Is there any plan to release a new version that supports php 8.1+?
I see there was some changes, but there is no new release.

**Comment by codemasher** [comment]
Hey, it's been a while since i looked at this repo - I think the issue back then was missing Windows binaries for APCU on PHP 8.1+. I'll see what i can do.

**Comment by codemasher** [comment]
I have just tagged a new version that supports PHP 8.1 and greater. Your issue should be resolved [as per my comment earlier](https://github.com/shetabit/multipay/issues/222#issuecomment-1946025944), however you can add v5 to the requirement as well - the API has not changed:

```json
{
	"require": {
		"php": "^7.4 || ^8.0",
		"chillerlan/php-cache": "^4.1 || ^5.0"
	}
}
```
